### ISSUE TITLE
Changing device name or removing device still reports metrics

### ISSUE THREAD

**Issue by ferni7** [dyrkin/tasmota-exporter#1]
I just installed and got this going thanks

But it looks like if i rename a device or remove a device, that it doesn't get removed from the prom exporter endpoint so it continues to look like the old device is still there.

I had to restart the tasmota-exporter container to get it to clean up/remove the old devices.

**Comment by dbrekau** [comment]
The main problem with this behaviour is, that values keeping in the last provided state forever. So Voltage, Power Consumption, etc. are not really meaningful. If a device is unplugged for example, it seems like it is still consumpting power.

It could be a solution to have a configureable timeframe with no updates, after metrics for a device will not be outputted anymore.

**Comment by ferni7** [comment]
@dyrkin Any interest in this modification?

**Comment by dyrkin** [comment]
hi guys. it should work now. i've added this env variable:
```go
REMOVE_WHEN_INACTIVE_MINUTES //optional. Default is 1. If the device is inactive for more than 1 minute, it will be removed from the list of active devices
```

please update to the latest version and check

**Comment by dbrekau** [comment]
> hi guys. it should work now. i've added this env variable:
> 
> ```go
> REMOVE_WHEN_INACTIVE_MINUTES //optional. Default is 1. If the device is inactive for more than 1 minute, it will be removed from the list of active devices
> ```
> 
> please update to the latest version and check

Hey @dyrkin thank you for the change. I was already able to test it and can confirm that it's working like exptected. This is great, thank you! :)
